### ISSUE TITLE
Addition of Privacy Manifest

### ISSUE THREAD

**Issue by MarkWatson16** [amazon-connect/amazon-connect-chat-ios#37]
Hi!

This framework looks great, really simplifies the integration and perfectly timed for my team to use too

I have a hopefully quick feature request, could a privacy manifest be added? Just as a precaution if Apple change their rules around what has to be included.

Thanks

**Comment by mrajatttt** [comment]
Hi, we have released new version to include above. 
https://github.com/amazon-connect/amazon-connect-chat-ios/releases/tag/v1.0.2

Please feel free to open if issue persists!
