### ISSUE TITLE
BUILD_LIBRARY_FOR_DISTRIBUTION not set to Yes on build settings

### ISSUE THREAD

**Issue by MarkWatson16** [amazon-connect/amazon-connect-chat-ios#40]
Hi,

Got an issue when trying to use the binary uploaded on your releases.

Both releases so far haven't had the `BUILD_LIBRARY_FOR_DISTRIBUTION` flag set. So when we try to use the binary we have to have the exact same swift tooling or it won't build. Even if we have a more recent swift tool version.

I tried cloning the repo and noticed the property is set to `No` for debug and release
<img width="700" alt="BUILD_LIBRARY_FOR_DISTRIBUTION" src="https://github.com/user-attachments/assets/4f7ff893-9e39-45e3-8f69-b6392aa78cd7">

Can you set that to Yes, and create a new binary for release? The previous two aren't actually usable currently 😅 

From here: https://www.swift.org/blog/library-evolution/
> When using Xcode to develop for Apple platforms, set the BUILD_LIBRARY_FOR_DISTRIBUTION build setting in the framework’s target. This setting turns on both library evolution and module stability. Be sure to use the setting in both Debug and Release builds.
> 
> The BUILD_LIBRARY_FOR_DISTRIBUTION Xcode build setting and associated .xcframework support were presented at WWDC 2019 in the talk titled [Binary frameworks in Swift](https://developer.apple.com/wwdc19/416).

**Comment by mliao95** [comment]
Hi @MarkWatson16!  Thanks for bringing this to our attention.  We will work on updating this in our next release.

**Comment by MarkWatson16** [comment]
Awesome, thanks @mliao95!

**Comment by mrajatttt** [comment]
Hi, we have released new version to include above. 
https://github.com/amazon-connect/amazon-connect-chat-ios/releases/tag/v1.0.2

Please feel free to open if issue persists!
